version: '3.1'
services:
  coupondb:
    container_name: coupon-postgres-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: coupon
      POSTGRES_PASSWORD: coupon
      POSTGRES_DB: coupon
    ports:
      - "54321:5432"
